name: Deploy to AWS

on:
  push:
    branches:
      - aws-deployment

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::632472162562:role/github-actions-portfolio
          aws-region: eu-north-1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      - name: Upload to S3
        run: aws s3 sync dist/ s3://personal-portfolio-aws-rsdev --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E35MO5FKPVPHM4 \
            --paths "/*"
